return {
	passing = {},
	facing = {},
	position = {},
	animation = {},
	velocity = {},
	offset = {},
	broken = {},
	player_temp_stats = {},
	mid_point = {},
	on_nodes = {},
	last_nodes = {},
	factions = {},
	pickups = {},
	transitions = {},
	to_draw = {},
	target_factions = {},
	grounded = {},
	has_dialogue = {},
	projectile_params = {},
	interactable_types = {},
	player_effects = {},
	occupied_nodes = {},
	npcs_culled = {},
	view_scale = 1,
	propagators = {},
}